#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	# selected=$(find ~/work/builds ~/Dev ~/projects ~/ ~/work ~/personal ~/personal/yt -mindepth 1 -maxdepth 1 -type d | fzf)
	selected=$(find ~/Dev ~/Dev/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# echo "\$TMUX: $TMUX"
# echo "\$tmux_running: $tmux_running"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected
	# echo "Inside there is tmux"
	exit 0
fi

if [[ -n $TMUX ]]; then
	# Inside tmux, switch or create a new session
	if ! tmux has-session -t=$selected_name 2>/dev/null; then
		# echo "Inside tmux, creating new session"
		tmux new-session -ds $selected_name -c $selected
	fi
	tmux switch-client -t $selected_name
else
	# Outside tmux, start a new session or attach to an existing one
	if ! tmux has-session -t=$selected_name 2>/dev/null; then
		# echo "Outside tmux, creating new session"
		tmux new-session -s $selected_name -c $selected
	else
		# echo "Outside tmux, attaching to existing session"
		tmux attach-session -t $selected_name
	fi
	# echo "Outside there is tmux"
fi
